package com.ibrahimdans.i18n.extensions.technology.i18next

/**
 * The text of an `i18next.d.ts` declaring the keys of a module, so that `tsc` checks `t('key')`.
 *
 * i18next types its `t` from a `CustomTypeOptions` interface the project augments: `resources`
 * gives each namespace its key tree, `defaultNS` the namespace a key without prefix belongs to.
 * Written once and committed, that file lets CI and teammates without the plugin catch a key that
 * does not exist — something only the IDE did so far.
 *
 * A pure function of the keys: no PSI, no file system, the same input always gives the same text,
 * sorted, so that regenerating an unchanged module leaves the committed file untouched.
 */
object I18nextTypesGenerator {

    /** The name of the action regenerating the file, quoted in its header. */
    const val ACTION_NAME = "Tools | i18n Support Plus | Generate i18next Types"

    /** How every generated file starts, whatever the action is called: tells it from a hand-written one. */
    const val GENERATED_BY = "// Generated by i18n Support Plus"

    /**
     * i18next's plural suffixes, cardinal and ordinal (`_one`, `_ordinal_few`…). They are joined
     * with `_`, i18next's own plural separator since v21: the code writes `t('item', { count })`.
     */
    private val PLURAL_SUFFIX = Regex("""^(.+?)_(?:ordinal_)?(?:zero|one|two|few|many|other)$""")

    private val IDENTIFIER = Regex("""^[A-Za-z_$][A-Za-z0-9_$]*$""")

    private const val INDENT = "  "

    /** i18next's own separators: left out of the declaration when the project keeps them. */
    private const val DEFAULT_KEY_SEPARATOR = "."
    private const val DEFAULT_NS_SEPARATOR = ":"

    /** `declare module 'i18next'` augmenting `CustomTypeOptions`, as a hand-written declaration does. */
    private val AUGMENTATION = Regex("""declare\s+module\s+['"]i18next['"]""")

    /**
     * The declaration file for [namespaces] — each namespace mapped to the paths of property names
     * of its keys, as read from the reference locale.
     *
     * [defaultNamespace] becomes `defaultNS` when it is one of [namespaces]; otherwise it is left
     * out, since naming a namespace that `resources` lacks would make every unprefixed key an error.
     *
     * [keySeparator] and [nsSeparator] are declared when they are not i18next's `.` and `:`, so
     * that the types split `t('ns|a-b')` as the project does; a null [keySeparator] declares flat
     * keys (`keySeparator: false`), where `app.title` is one key.
     */
    fun generate(
        namespaces: Map<String, Collection<List<String>>>,
        defaultNamespace: String?,
        keySeparator: String? = DEFAULT_KEY_SEPARATOR,
        nsSeparator: String = DEFAULT_NS_SEPARATOR
    ): String {
        val out = StringBuilder()
        out.append("$GENERATED_BY — do not edit; regenerate with $ACTION_NAME.\n")
        out.append("import 'i18next';\n\n")
        out.append("declare module 'i18next' {\n")
        out.append(INDENT).append("interface CustomTypeOptions {\n")
        if (defaultNamespace != null && defaultNamespace in namespaces) {
            out.append(INDENT.repeat(2)).append("defaultNS: ").append(quote(defaultNamespace)).append(";\n")
        }
        if (keySeparator != DEFAULT_KEY_SEPARATOR) {
            out.append(INDENT.repeat(2)).append("keySeparator: ").append(keySeparator?.let { quote(it) } ?: "false").append(";\n")
        }
        if (nsSeparator != DEFAULT_NS_SEPARATOR) {
            out.append(INDENT.repeat(2)).append("nsSeparator: ").append(quote(nsSeparator)).append(";\n")
        }
        val resources = Node()
        for ((namespace, paths) in namespaces) {
            val node = resources.branch(namespace)
            paths.filter { it.isNotEmpty() }.forEach { node.add(it) }
        }
        out.append(INDENT.repeat(2)).append("resources: ")
        appendBranch(out, resources, depth = 2)
        out.append(";\n")
        out.append(INDENT).append("}\n")
        out.append("}\n")
        return out.toString()
    }

    /** A key segment: a leaf when it holds no children and was written as a string value. */
    private class Node {
        val children = sortedMapOf<String, Node>()
        var leaf = false

        fun branch(name: String): Node = children.getOrPut(name) { Node() }

        fun add(path: List<String>) {
            val child = branch(path.first())
            if (path.size == 1) child.leaf = true else child.add(path.drop(1))
        }

        /** A segment holding nested keys is an object, even when another file made it a string. */
        val isBranch get() = children.isNotEmpty() || !leaf
    }

    private fun appendBranch(out: StringBuilder, node: Node, depth: Int) {
        val members = membersOf(node)
        if (members.isEmpty()) {
            out.append("{}")
            return
        }
        out.append("{\n")
        for ((name, child) in members) {
            out.append(INDENT.repeat(depth + 1)).append(propertyName(name)).append(": ")
            if (child.isBranch) appendBranch(out, child, depth + 1) else out.append("string")
            out.append(";\n")
        }
        out.append(INDENT.repeat(depth)).append("}")
    }

    /**
     * [node]'s children as the code names them: plural forms (`item_one`, `item_other`) collapse
     * into the single key `item` — unless `item` already holds nested keys, where the forms keep
     * their own names rather than turn an object into a string.
     */
    private fun membersOf(node: Node): Map<String, Node> {
        val members = sortedMapOf<String, Node>()
        for ((name, child) in node.children) {
            val base = if (child.isBranch) null else PLURAL_SUFFIX.matchEntire(name)?.groupValues?.get(1)
            val collapsed = base != null && node.children[base]?.isBranch != true
            if (collapsed) members.putIfAbsent(base!!, child) else members[name] = child
        }
        return members
    }

    /**
     * True when [text] is another declaration typing i18next — a hand-written `declare module
     * 'i18next'` with its own `CustomTypeOptions` — which the generated one would contradict.
     * A file this generator wrote is not one.
     */
    fun declaresCustomTypes(text: String): Boolean =
        !text.startsWith(GENERATED_BY) && AUGMENTATION.containsMatchIn(text) && "CustomTypeOptions" in text

    /** [name] as a TypeScript property name: bare when it is an identifier, quoted otherwise. */
    internal fun propertyName(name: String): String = if (IDENTIFIER.matches(name)) name else quote(name)

    /** [value] as a single-quoted TypeScript string literal. */
    internal fun quote(value: String): String {
        val out = StringBuilder("'")
        for (c in value) {
            when (c) {
                '\\' -> out.append("\\\\")
                '\'' -> out.append("\\'")
                '\n' -> out.append("\\n")
                '\r' -> out.append("\\r")
                '\t' -> out.append("\\t")
                ' ', ' ' -> out.append("\\u%04x".format(c.code))
                else -> if (c < ' ') out.append("\\u%04x".format(c.code)) else out.append(c)
            }
        }
        return out.append("'").toString()
    }
}
