package com.ibrahimdans.i18n.extensions.technology.i18next

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

class I18nextTypesGeneratorTest {

    private fun keys(vararg paths: String): List<List<String>> = paths.map { it.split('.') }

    /** The `resources` block alone, without the header and the module augmentation around it. */
    private fun resourcesOf(text: String): String =
        text.substringAfter("resources: ").substringBeforeLast(";\n  }\n}")

    @Test
    fun `the file augments i18next's CustomTypeOptions under a header naming the action`() {
        val text = I18nextTypesGenerator.generate(mapOf("common" to keys("title")), "common")

        assertEquals(
            """
            // Generated by i18n Support Plus — do not edit; regenerate with Tools | i18n Support Plus | Generate i18next Types.
            import 'i18next';

            declare module 'i18next' {
              interface CustomTypeOptions {
                defaultNS: 'common';
                resources: {
                  common: {
                    title: string;
                  };
                };
              }
            }

            """.trimIndent(),
            text
        )
        assertTrue(text.startsWith(I18nextTypesGenerator.GENERATED_BY))
    }

    @Test
    fun `every namespace gets its nested keys as objects of strings`() {
        val text = I18nextTypesGenerator.generate(
            mapOf(
                "common" to keys("actions.save", "actions.cancel", "appName"),
                "dashboard" to keys("stats.users.label", "title")
            ),
            "common"
        )

        assertEquals(
            """
            {
                  common: {
                    actions: {
                      cancel: string;
                      save: string;
                    };
                    appName: string;
                  };
                  dashboard: {
                    stats: {
                      users: {
                        label: string;
                      };
                    };
                    title: string;
                  };
                }
            """.trimIndent(),
            resourcesOf(text)
        )
    }

    @Test
    fun `plural forms collapse into the key the code writes`() {
        val text = I18nextTypesGenerator.generate(
            mapOf("ns" to keys("item_one", "item_other", "item_zero", "place_ordinal_one", "place_ordinal_few", "place_ordinal_other", "count_one", "count")),
            null
        )

        val resources = resourcesOf(text)
        assertTrue(resources.contains("item: string;"))
        assertTrue(resources.contains("place: string;"))
        assertEquals(1, Regex("""\bcount: string;""").findAll(resources).count(), "a plain key and its forms give one key")
        assertFalse(resources.contains("_one"))
        assertFalse(resources.contains("_other"))
        assertFalse(resources.contains("_ordinal"))
    }

    @Test
    fun `a plural form beside an object of the same name keeps its own name`() {
        val text = I18nextTypesGenerator.generate(mapOf("ns" to keys("item.label", "item_one", "item_other")), null)

        val resources = resourcesOf(text)
        assertTrue(resources.contains("item: {"))
        assertTrue(resources.contains("item_one: string;"))
        assertTrue(resources.contains("item_other: string;"))
    }

    @Test
    fun `a suffix that is not an i18next plural form is kept`() {
        val resources = resourcesOf(I18nextTypesGenerator.generate(mapOf("ns" to keys("friend_male", "item_plural", "one")), null))

        assertTrue(resources.contains("friend_male: string;"))
        assertTrue(resources.contains("item_plural: string;"))
        assertTrue(resources.contains("one: string;"))
    }

    @Test
    fun `names that are not identifiers are quoted and escaped`() {
        val text = I18nextTypesGenerator.generate(
            mapOf("deposit-box" to listOf(listOf("app.title"), listOf("it's"), listOf("back\\slash"), listOf("2fa"), listOf("line\nbreak"), listOf("\$ok_1"))),
            "deposit-box"
        )

        assertTrue(text.contains("defaultNS: 'deposit-box';"))
        assertTrue(text.contains("'deposit-box': {"))
        assertTrue(text.contains("'app.title': string;"), "a flat key with a dot is one property")
        assertTrue(text.contains("'it\\'s': string;"))
        assertTrue(text.contains("'back\\\\slash': string;"))
        assertTrue(text.contains("'2fa': string;"))
        assertTrue(text.contains("'line\\nbreak': string;"))
        assertTrue(text.contains("\$ok_1: string;"))
    }

    @Test
    fun `the default namespace is left out when no file holds it`() {
        val text = I18nextTypesGenerator.generate(mapOf("common" to keys("title")), "translation")

        assertFalse(text.contains("defaultNS"))
    }

    @Test
    fun `the output is sorted whatever the order the files were read in`() {
        val first = I18nextTypesGenerator.generate(
            linkedMapOf("zeta" to keys("b", "a.y", "a.x"), "alpha" to keys("k")),
            "alpha"
        )
        val second = I18nextTypesGenerator.generate(
            linkedMapOf("alpha" to keys("k"), "zeta" to keys("a.x", "b", "a.y")),
            "alpha"
        )

        assertEquals(first, second)
        assertTrue(first.indexOf("alpha:") < first.indexOf("zeta:"))
        assertTrue(first.indexOf("x: string") < first.indexOf("y: string"))
    }

    @Test
    fun `a key both nested and plain in two files stays an object, and an empty namespace is an empty object`() {
        val text = I18nextTypesGenerator.generate(
            mapOf("common" to keys("menu", "menu.home"), "empty" to emptyList()),
            null
        )

        assertTrue(text.contains("menu: {"))
        assertTrue(text.contains("home: string;"))
        assertTrue(text.contains("empty: {};"))
    }

    @Test
    fun `i18next's own separators are left out of the declaration`() {
        val text = I18nextTypesGenerator.generate(mapOf("common" to keys("title")), "common")

        assertFalse("keySeparator" in text, text)
        assertFalse("nsSeparator" in text, text)
    }

    @Test
    fun `the project's separators are declared when they are not i18next's`() {
        val text = I18nextTypesGenerator.generate(mapOf("common" to keys("title")), "common", keySeparator = "-", nsSeparator = "|")

        assertTrue("    keySeparator: '-';\n" in text, text)
        assertTrue("    nsSeparator: '|';\n" in text, text)
    }

    @Test
    fun `flat keys declare no key separator at all`() {
        val text = I18nextTypesGenerator.generate(mapOf("common" to listOf(listOf("app.title"))), "common", keySeparator = null)

        assertTrue("    keySeparator: false;\n" in text, text)
        assertTrue("'app.title': string;" in text, text)
    }

    @Test
    fun `a hand-written declaration typing i18next competes with the generated one`() {
        val handWritten = """
            import 'i18next';
            import common from '../public/locales/en/common.json';

            declare module "i18next" {
              interface CustomTypeOptions {
                resources: { common: typeof common };
              }
            }
        """.trimIndent()

        assertTrue(I18nextTypesGenerator.declaresCustomTypes(handWritten))
        assertFalse(
            I18nextTypesGenerator.declaresCustomTypes(I18nextTypesGenerator.generate(mapOf("common" to keys("title")), "common")),
            "the generated file is the one being rewritten, not a competitor"
        )
        assertFalse(I18nextTypesGenerator.declaresCustomTypes("declare module 'react' { interface CustomTypeOptions {} }"))
        assertFalse(I18nextTypesGenerator.declaresCustomTypes("declare module 'i18next' { interface TFunction {} }"))
    }
}
